### ISSUE TITLE
[BUG]Logout button fails to bring user to the home page when previously logged in with Google account

### ISSUE THREAD

**Issue by CSumm** [factn/resilience-app#109]
Steps to reproduce
1. Enter into app
2. Go to login page
3. Sign in with Google account
4. Press toggle menu and go to volunteered missions
5. When on empty missions page, press on toggle again and press sign out
6. User remains on empty missions page

Expected result:
User is redirected to home page after logging out

Actual result: 
User remains on empty missions page after logging out

**Comment by azmainamin** [comment]
This is fixed.
