### ISSUE TITLE
[BUG]User goes to a "cannot get" route page instead of login page when entering a protected route in the search bar

### ISSUE THREAD

**Issue by CSumm** [factn/resilience-app#111]
Steps to reproduce

1. Open[ the heroku app](https://mutualaidworld-frontend.herokuapp.com/)
2. Enter a protected route inside of the search bar
3. Observe the output of the page.

Expected result:
User can be redirected to login page with the warning "You must be logged in".

Actual result:
User is greeted to a "cannot get" route page instead of the login page that specifies a login warning.

**Comment by AquiburRahmanKhan** [comment]
@utunga can you please assign this issue to me ? thanks
