### ISSUE TITLE
[BUG] Button to upload image to profile is missing on user profile page

### ISSUE THREAD

**Issue by CSumm** [factn/resilience-app#112]
Steps to reproduce:
1. Go to [Resilience heroku staging app](https://mutualaidworld-frontend.herokuapp.com/)
2. Sign in with Google account
3. Click on user profile
4. Observe the user profile screen

Expected result: User can see an upload profile picture option that can take from their desktop or their mobile device.

Actual result: Button to upload image is missing from user profile page

**Comment by stinodes** [comment]
I'm looking into picking this issue up. 
Any examples where this button is present (or any available designs) for consistency's sake, or is this to be implemented at my own discretion?

Cheers!

**Comment by mat10tng** [comment]
![image](https://user-images.githubusercontent.com/3273671/78645521-f308a600-78b7-11ea-9dd1-f456ca9cbdaa.png)
Hi, this is the design in figma

**Comment by stinodes** [comment]
Awesome, I'll pick this up later today when I find some time!

**Comment by jwu910** [comment]
https://github.com/factn/resilience-app/pull/213

This issue was resolved
