### ISSUE TITLE
[BUG] Missions list is missing when missions page is being accessed by non-logged in users

### ISSUE THREAD

**Issue by CSumm** [factn/resilience-app#113]
Steps to Reproduce:

1. Go to  [Resilience staging app](https://mutualaidworld-frontend.herokuapp.com/)
2. Click on View missions
3. Observe missions screen

Expected result:
Anonymous users can view the missions page and volunteer right away.

Actual result:
Missions page appears empty when anonymous user visits the page without signing in.

Screenshot:
![missingmissionslist](https://user-images.githubusercontent.com/31711543/78311084-de29bc80-751d-11ea-8d9d-007619858e77.png)

**Comment by mat10tng** [comment]
I think it is because there was no mission available? I added a dummy mission and it does show up. Maybe it should said that on the screen though.

**Comment by CSumm** [comment]
Ah yeah, that could be good. If we can show a message saying "no missions are available at this time" or something. Most likely my issue came from already registering with my Google account. I can look into deleting or cancelling missions from my user screen

**Comment by mat10tng** [comment]
ah, no, honestly, it was because there was no missions anywhere :p, Can you take a look now ? I added a bunch

**Comment by CSumm** [comment]
Cool, perfect. It works now
