### ISSUE TITLE
We need some naming rules for branches

### ISSUE THREAD

**Issue by utunga** [factn/resilience-app#135]
@qdozaq asked on card that he would "like to see the rules of git branching naming convention so that I know how to name my branch correctly"

Good point. lets do that and add that to [CONTRIBUTING.md](https://github.com/factn/resilience-app/blob/master/CONTRIBUTING.md) 

PS So far the branch naming scheme is :

`feat/whatever_you_want`

But perhaps we could get a bit fancier than that.

--

Long as we are updating CONTRIBUTING.md maybe we could put a note in there begging people to delete their branches after they create a PR also.

**Comment by AquiburRahmanKhan** [comment]
How about something like this `{type}/{IssueNo}-issue-one-liner` where type can be either **feat**, **fix**, **docs**, **style** , **refactor**, **perf**, **test**, **build**. For example `feat/issue-135-add-loader`

**Comment by mat10tng** [comment]
yeah, maybe also feat/story-12-add-missions, since we have both mission/issue type

**Comment by qdozaq** [comment]
Would be good to explicitly differentiate between stories in airTable and issues in github as the numbers could overlap.
Like `feat` is just for stories and the rest are for github issues

**Comment by mat10tng** [comment]
I think that a good idea, but I would like more explicit in that case, so, maybe
{type}/{typeId}-{typeAction}-{description}
type = story|issue
typeAction= 
    story  - we only have one story so I don't know what action would be here
    issue -  fix, docs, style, refactor, perf, test, build
