### ISSUE TITLE
aXe console error 

### ISSUE THREAD

**Issue by azmainamin** [factn/resilience-app#136]
Going to SignIn page gives this:
![image](https://user-images.githubusercontent.com/12126548/78671191-f480a100-78ac-11ea-812c-7cf9f99fc985.png)

**Comment by azmainamin** [comment]
This is propagated across the whole app.

**Comment by mat10tng** [comment]
Yeah, I have no clue about this bug. From what I have seen, I am thinking of it is how React add and remove node from the dom -> but Axe did not catch that and wonder, where did the damn node go, and so we got a weird error coming out.

**Comment by sebassdc** [comment]
@azmainamin i think this have to do with Transition Group, i think react-axe is not able to keep up with this.
I was  researching a way to filter this error so this don't show up in the console but didn't find anything.

**Comment by sebassdc** [comment]
Also there are some console errors due to the svg using identical ids because we are using the same svg twice in the home page.

**Comment by heisfullstacked** [comment]
Can I have a look into this?

**Comment by mTRx0** [comment]
@mat10tng @azmainamin I guess this issue can be closed as it seems to be fixed.
