### ISSUE TITLE
Increase spacing between icon and text in the sidebar

### ISSUE THREAD

**Issue by azmainamin** [factn/resilience-app#137]
Fix spacing around icon and text:
![image](https://user-images.githubusercontent.com/12126548/78671542-707ae900-78ad-11ea-83ee-9e0168ae526f.png)

This is a nice mockup:
![image](https://user-images.githubusercontent.com/12126548/78671634-88526d00-78ad-11ea-884a-8c37bc8a64d5.png)

**Comment by skbrown333** [comment]
It looks like I am unable to assign myself to this issue @utunga

**Comment by nickx720** [comment]
Hi @skbrown333 , I have already fixed it in local but unable to push it 🤣
