### ISSUE TITLE
Add propTypes and jsDocs for components

### ISSUE THREAD

**Issue by azmainamin** [factn/resilience-app#139]
Use PropTypes(https://reactjs.org/docs/typechecking-with-proptypes.html) for components and JSDOCs(https://jsdoc.app/about-getting-started.html)for functions

Code to cover:

• src/app/component/PhoneLoginForm

• src/app/component/MapView

• src/app/component/Input

• src/app/component/ImageUpload

• src/app/component/FirebaseAuthUi

• src/app/component/MissionCard

• src/app/component/PrivateComponent

• src/app/component/ProtectedRoute

**Comment by micahmones** [comment]
hi, when i get added as a contributor i can take this if needed

**Comment by qdozaq** [comment]
@micahmones You still working on this?

**Comment by Eihcir0** [comment]
@qdozaq 
Should this ticket be closed with the merge of https://github.com/factn/resilience-app/pull/186?

**Comment by qdozaq** [comment]
@Eihcir0 That was for pages so this one still needs to be done. I haven't heard from Micah so I'm gonna open this one up for whoever wants it

**Comment by Eihcir0** [comment]
@qdozaq I'll take it if you want to assign to me

**Comment by qdozaq** [comment]
@Eihcir0 You got it!
