### ISSUE TITLE
Add propTypes and jsDoc for components in Pages

### ISSUE THREAD

**Issue by azmainamin** [factn/resilience-app#143]
Use PropTypes(https://reactjs.org/docs/typechecking-with-proptypes.html) for components and JSDOCs(https://jsdoc.app/about-getting-started.html)for functions

These are nice to have. Code to cover:

• src/app/page
		• About Us

		• Home

		• Login

		• MakeRequest

		• MissonDetails

		• Missions

		• MissionsControl

		• MissionsCreated

		• MissionsVolunteered

		• OrganizerSignup

		• Signup

		• Status

		• UserProfile

**Comment by guillermoparral1995** [comment]
has anyone taken this? if not, I'd like to have this one (and the other ones about propTypes if they are still available)

**Comment by guillermoparral1995** [comment]
why was this closed?

**Comment by mat10tng** [comment]
Oh sorry. I was on a cleaning spray

**Comment by guillermoparral1995** [comment]
removed my assignment by accident 😅

**Comment by azmainamin** [comment]
@guillermoparral1995  added you back!

**Comment by guillermoparral1995** [comment]
This should be closed, PR was merged 😄
