### ISSUE TITLE
Remove unused imports

### ISSUE THREAD

**Issue by roberts98** [factn/resilience-app#149]
When you start the application there are so much unused imports, I think we should get rid of them, because we can miss more important warnings, like memory leaks etc.

**Comment by mat10tng** [comment]
I agree. I have been very reckless there, ehm, you wanna do a pr on that ?

**Comment by roberts98** [comment]
Yes, I've already done that, waiting for write access, if you can do it, I'd be grateful.

**Comment by roberts98** [comment]
#165
