### ISSUE TITLE
Updating phone number from User Profile page is not working.

### ISSUE THREAD

**Issue by azmainamin** [factn/resilience-app#152]
Current Behavior: Phone number is not updated. There is console error.
![image](https://user-images.githubusercontent.com/12126548/78729262-a5b42500-7907-11ea-8ee5-15f0fd22fac4.png)

Expected behavior: The updated number should be reflected in the user profile page. The updated number should be saved in Firebase DB.

**Comment by pedro-surf** [comment]
https://github.com/factn/resilience-app/pull/153 sent to review.
