### ISSUE TITLE
Add "Add 2 Home Screen" aka A2HS support.

### ISSUE THREAD

**Issue by utunga** [factn/resilience-app#155]
Bit of design work needed here but mostly what we're after is integration in a standards-compliant way so iPhone and Android users have a clean and effective option to 'add to home screen'. 

Maybe it appears after login then disappears or something? Not sure... But implementing it would be the first step, then we can decide when it should appear. 

https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen

**Comment by utunga** [comment]
I decided to add a story for this as well.. 
https://airtable.com/tblRjd2McKgRW9MKj/viwAsqEsBiGxnqy7H/recWXUcBDE36Uioku?blocks=hide

**Comment by nickx720** [comment]
Hi, i could take this up if you'd like.

**Comment by mat10tng** [comment]
Hi, if therer is an airtable story, then we should take there instead
