### ISSUE TITLE
Mission control route doesn't have a menu link nor a menu itself

### ISSUE THREAD

**Issue by pedro-surf** [factn/resilience-app#166]
Description:
The route **/missions/control**, which apparently shows classified missions by their status, has no link in the app main menu. I'll fix it on this PR (#163) I'm currently working that already modified this page. 
#163 

Note:
Also, it has a different menu itself, which links seem to be currently not working. 
Yet, a route like this certainly needs pagination. Does Firebase handle it already? Check it if possible.

**Comment by mat10tng** [comment]
yes, firebase have pagination
the menu it self was just a dummy 
the missions/control route was support to be worked on, but then we got another direction, but now we are back to track.
