### ISSUE TITLE
When clicking on Icon in the menu, nothing happens

### ISSUE THREAD

**Issue by pedro-surf** [factn/resilience-app#167]
Description:
If user clicks an Icon in the hamburger menu, it should direct to the proper route, just like when clicking on the text right to it's right.
Currently nothing happens. I'm fixing it on PR #163

**Comment by jwu910** [comment]
Hey @pedro-surf I missed this issue when creating #177. I submitted https://github.com/factn/resilience-app/pull/178 as a fix for it.

If you don't want to scope creep your other ticket, we can use my PR, let me know. I'm open.

**Comment by jwu910** [comment]
This can be closed. Fixed in #178
