### ISSUE TITLE
The requester in MissionDetails.jsx is hardcoded. We need to get that data dynamically. 

### ISSUE THREAD

**Issue by azmainamin** [factn/resilience-app#171]
Component: MissionDetails.jsx
![image](https://user-images.githubusercontent.com/12126548/78856275-51d33a00-79f4-11ea-97b9-dc4bdaf44695.png)

Expected: We should get requester data  from the DB i.e. from the mission object. 
Mission Object structure:
![image](https://user-images.githubusercontent.com/12126548/78856360-8fd05e00-79f4-11ea-81d9-031db9680b77.png)

We might need to fetch the user using the ownerId of the mission object.

**Comment by roberts98** [comment]
Can you assign this task to me?

**Comment by mat10tng** [comment]
I think the discussion in slack is that we are going to remove it. So we
can wait for another issue to open maybe?

**Comment by azmainamin** [comment]
@roberts98 This is the new issue: https://github.com/factn/resilience-app/issues/180
