### ISSUE TITLE
Remove requester information from Missiondetails.jsx

### ISSUE THREAD

**Issue by azmainamin** [factn/resilience-app#180]
We do not want the requester information to show up right now. This issue involves removing the hardcoded requester information, and the associated Avatar component in MissionDetails.jsx

https://user-images.githubusercontent.com/12126548/78856275-51d33a00-79f4-11ea-97b9-dc4bdaf44695.png

**Comment by Adogeon** [comment]
Hi azmainamin,  can I have this task ?
