### ISSUE TITLE
Google account fails to be disconnected when user clicks 'Disconnect' Google account button on user profile page

### ISSUE THREAD

**Issue by CSumm** [factn/resilience-app#189]
This issue assumes you currently have an account with Resilience app using Google authentication

Steps to Reproduce

1. Go to [Resilience App](https://mutualaidworld-frontend.herokuapp.com/)
2. Click the sign in button
3. Sign in with Google Authentication
4. Click on the hamburger and go to user profile
5. Scroll down to disconnect from Google authentication and click the button
6. Go to menu and log out
7. Repeat steps 2 and 3

Expected result:
User can go through first-time authentication with their Google account when connecting to the app

Actual result:
Google account appears to still be connected to the app even after clicking disconnect from the user profile page

**Comment by mat10tng** [comment]
It is disconnected, but they are sharing the same email address, so once you logged in with that google account again, its going to be link to that same account again.

**Comment by azmainamin** [comment]
Resolved.
