### ISSUE TITLE
Standardize on one MissionCard.jsx component

### ISSUE THREAD

**Issue by Eihcir0** [factn/resilience-app#194]
We currently have two (very similar) versions of `MissionCard.js`.  One version is used by both the  _Volunteers Needed_ and _Volunteered Missions_ pages.   The other type is used by MissionControl.

We should combined those into one component because DRY.  

[See comment.](https://github.com/factn/resilience-app/pull/193#pullrequestreview-391672495)

**Comment by mat10tng** [comment]
I am so sorry about that, everything in missions control is a private component, if it was public, I would have put it in the component or layout folder. Sorry for the missunderstanding
