### ISSUE TITLE
Mission shows as volunteerable when already volunteered for

### ISSUE THREAD

**Issue by Spraynard** [factn/resilience-app#197]
### Issue Statement

On the `/missions/volunteered` view, as a volunteer you see the missions you have already volunteered for.

If you add any mission there, you will see that a **volunteer** button is still visible. This could possibly be confusing to people.

### Expected Bahavior

If it is in the volunteered missions list, you should not have an option to volunteer for it again.

### Notes
![Screen Shot 2020-04-10 at 11 00 46 PM](https://user-images.githubusercontent.com/17299952/79033821-4d875800-7b7f-11ea-9410-bd492ea9f5bd.png)

**Comment by pedro-surf** [comment]
Are you or anyone working on this already?

**Comment by Spraynard** [comment]
Hey yeah I'm working on this now. I should have a pr up soon

**Comment by Spraynard** [comment]
Hey sorry I didn't complete this issue yet. I put up the code I was able to get through last night up until we reached our quota limit but didn't get to this as of yet

**Comment by Spraynard** [comment]
You know what I think this is all good. Hope I didn't cause too much trouble for ya.
