### ISSUE TITLE
Unable to back out of volunteering for a mission

### ISSUE THREAD

**Issue by Spraynard** [factn/resilience-app#198]
### Issue Statement

After a volunteer volunteers for a mission, they are unable to un-volunteer from the mission.

### Expected Bahavior

As a volunteer, I would expect that I would be able to back out of volunteering for a service. Something may have come up in my life, or other situations could arise.

**Comment by laredotornado** [comment]
Please assign this to me.  Per Tuan, this is just the functional hook and design is being handled as part of another ticket.

**Comment by azmainamin** [comment]
@laredotornado we can close this right?
