### ISSUE TITLE
change placeholder text

### ISSUE THREAD

**Issue by mat10tng** [factn/resilience-app#221]
change placeholder text in the homepage
to:
Need help? 
Sign up to make a request for a food box, small errand, or a pharmacy pickup. Your ask goes right to the local coordinator, and is matched with a volunteer who will take care of your need ASAP.

Want to help?
Sign up to join your local network of volunteers helping their neighbors through this crisis. Deliver food, medicine, and other supplies to the most vulnerable.
![image](https://user-images.githubusercontent.com/3273671/79101749-84b95d00-7d69-11ea-97e1-8ae2b0170cf9.png)

**Comment by amanchauhan11** [comment]
@mat10tng Can I do this?
