### ISSUE TITLE
Date picker should appear when first clicking on "Select Date" field

### ISSUE THREAD

**Issue by laredotornado** [factn/resilience-app#234]
When creating a mission, clicking on the "Select Date" brings up a cursor, but in order to see the date picker UI, you must click on the calendar icon to the right ...

<img width="695" alt="Screen Shot 2020-04-14 at 5 36 44 PM" src="https://user-images.githubusercontent.com/14842313/79280704-a6ecd100-7e76-11ea-9e5d-b837b78b7e4e.png">

Upon first clicking on the "Select Date," text field, the date picker should appear.

**Comment by azmainamin** [comment]
@laredotornado Is this still ongoing?

**Comment by laredotornado** [comment]
Hi @azmainamin , about to submit PR ...
