### ISSUE TITLE
When creating a mission, selecting a date in the date picker UI doesn't automatically select that date

### ISSUE THREAD

**Issue by laredotornado** [factn/resilience-app#235]
When creating a mission and choosing the mission date, after bringing up the date picker, clicking on a date in the date picker does not automatically select the date.  You must then click "OK"

<img width="724" alt="Screen Shot 2020-04-14 at 5 40 55 PM" src="https://user-images.githubusercontent.com/14842313/79281000-7b1e1b00-7e77-11ea-9629-67e531b3d30d.png">

Preference is for the date to automatically select without having to go through the extra step of also clicking the date picker's "OK" button.

**Comment by nullHappy** [comment]
Quick question, should the validation also prevent you from adding dates that are in the past?

**Comment by laredotornado** [comment]
So @azmainamin , this issue got resolved with the PR I submitted today related to this issue -- https://github.com/factn/resilience-app/issues/234, but maybe the issue @nullHappy raises about validation can be created as a separate issue or this issue can capture that?

**Comment by nullHappy** [comment]
@laredotornado sorry that was my bad, I wanted to confirm if it was a valid issue before raising. 
I can log a separate ticket if that makes your life easier

**Comment by azmainamin** [comment]
@nullHappy  A separate issue would be awesome! I will close this one.

**Comment by nullHappy** [comment]
Issue discussed above was logged as: https://github.com/factn/resilience-app/issues/289
