### ISSUE TITLE
Snackbar breakout

### ISSUE THREAD

**Issue by mat10tng** [factn/resilience-app#242]
Currently, we are using snack bar component, each time we need to display a message due to error from whatever the reason, or success, we have to pick out individually the correct snack bar, also need to add the snack bar component to the system.

We should use https://github.com/TeamWertarbyte/material-ui-snackbar-provider 
to provide the tools to have a more consist and easier time with a notification

**Comment by azmainamin** [comment]
@mat10tng  Hey Tuan. Is having a success and error snackbar a problem? I like that we have consistent snackbars for success and error situations. I don't want to add another npm package :P

**Comment by mat10tng** [comment]
Honeslmtly we can juse build our ow  from that, it is just a normal
provider wrap. But imagine that we do need to add the error and success
handler when a request is made and so these two elements will need to be
added basically everywhere we make a request.

**Comment by azmainamin** [comment]
Maybe a withError hoc?

**Comment by mat10tng** [comment]
yeah, or rather, just provide it in root

**Comment by JARV0210** [comment]
@azmainamin @mat10tng would you guys like to word on a big project?

**Comment by jwu910** [comment]
Didn't see this issue before. Bringing up the convo i had somewhere briefly about this.

We can set up a notification provider with an update callback that provides a status + message through context. Then we can import that context and consumer anywhere in the app

**Comment by azmainamin** [comment]
@jwu910 Consider me intrigued. Is there any examples around? I would like to learn more!

**Comment by mat10tng** [comment]
https://reactjs.org/docs/context.html
Yeah, this is what I meant as well

**Comment by jwu910** [comment]
I can try to set this up. Context is like a low-complexity solution to the problem redux solves.

But yeah, i'll find some free time to try and work on something like this. It would be something an global error handler could utilize too
