### ISSUE TITLE
finish refactor of repository architecture 

### ISSUE THREAD

**Issue by utunga** [factn/resilience-app#247]
Tuan to finish off one example ? and then maybe someone else can jump on and finish applying this across all the code

**Comment by mat10tng** [comment]
The first version are now in.

**Comment by qdozaq** [comment]
@mat10tng can we get a list of the remaining models that need to be done? then @azmainamin and I could split them up

**Comment by mat10tng** [comment]
Yes!
models:
Organization
Foodbox
Page:
MakeMission -> I would like to change this to MissionCreate and use the Mission model to load and then sanitize the data to be save in the backend with User.createMission
We also have to change some of the field that are not in use in this view, but in organizer view
MakeRequest-> remove this, we use MakeMisssion now
MissionDetails -> use the model to load, and we need to sanitize it before send back to database
OrganizerSignup -> ??? maybe MVP1 but same with MissionCreate
Signup -> making sure use created with full information, same with MissionCreate
Status -> not sure if we using this right now, maybe remote from route, but keep the page




Organizations ( though admittedly, that

**Comment by Eihcir0** [comment]
I can take signup on this

**Comment by azmainamin** [comment]
@Eihcir0  Signup is yours.
@mTRx0  MakeMission is yours. I think removing MakeRequest falls under this as well?

I will work on

**Comment by qdozaq** [comment]
I'll do OrganizerSignup? is that needed?

**Comment by mTRx0** [comment]
> @mTRx0 MakeMission is yours. I think removing MakeRequest falls under this as well?

Yeah I can do that aswell.

**Comment by azmainamin** [comment]
@mTRx0 I am reviewing your PR. Can you make any other changes in a different PR? Thank!

**Comment by mTRx0** [comment]
sure :)

**Comment by utunga** [comment]
@qdozaq  should we close this issue or is it still outstanding?

**Comment by qdozaq** [comment]
Yeh we can close this
