### ISSUE TITLE
As an organizer on a desktop device I can get to and from mission control (Airtable 160)

### ISSUE THREAD

**Issue by utunga** [factn/resilience-app#249]
User story 160
https://airtable.com/tblRjd2McKgRW9MKj/viwFfwz1LXBSjhZ2g/rec2JtXXhSV2NfdVF?blocks=hide

**Comment by mat10tng** [comment]
you need to be an organizer to see that route. Right now we don't have a way to do this, so you have to go in the firebase database manually, find your user, and add/set field isOrganizer=true

**Comment by marekdano** [comment]
@utunga I'm looking at this issue. I can add a link of `Dashboard` to the right-side navbar when a user is `isOrganizer=true`.  And `App` link to the left-side navbar in the `Mission Control` page. What do you think?

**Comment by mat10tng** [comment]
refer to story #396 instead. If you want to do this task,  just assign it to your self. I have already done the link to dashboard though, so maybe just a link back from dashboard to normal home needed
