### ISSUE TITLE
Map component // Csumm

### ISSUE THREAD

**Issue by mat10tng** [factn/resilience-app#25]
![image](https://user-images.githubusercontent.com/3273671/77260738-1a415f80-6c8a-11ea-8ea2-3b68b862abf7.png)

**Comment by CSumm** [comment]
Is there a particular API we want to use for the Map such as Google Maps? Also is anyone currently working on this issue?

**Comment by mat10tng** [comment]
No api yet, and no one have been taking the issue.  You are free to choose what is needed for now.

**Comment by CSumm** [comment]
Also another question, is the colors in the photo what we want them to be? And there already exists code for the map inside of the codebase. You simply want us to just design the sass file?

**Comment by CSumm** [comment]
@mat10tng is it possible to make API calls through storybook? I want to make the map searchable via storybook but I couldn't find any info on whether this is possible
