### ISSUE TITLE
refactor back end of user drop down to be faster and better by moving business logic to server 

### ISSUE THREAD

**Issue by utunga** [factn/resilience-app#253]
This PR https://github.com/factn/resilience-app/pull/252 addressed Story 115.

But the back end  (currently in User.ts) is a scary nightmarish mess and caches the entire list of users client side - this will cause bugs such as if someone is trying to add users on the mission control page, and those users have only just signed up. 

So.. the right way to do this is to move the 'filter' business logic to the back end

**Comment by utunga** [comment]
Assigning to you more as an FYI @mat10tng feel free to unassign yourself

**Comment by mat10tng** [comment]
we will get back to this later if its become an issue
