### ISSUE TITLE
[bug] Domain on the access dialog doesn't match the applications domain

### ISSUE THREAD

**Issue by nullHappy** [factn/resilience-app#255]
The current domain of the test app is: https://resilience-app.herokuapp.com/
When the user clicks on the button to grant access to their google account the domain to grant access to is from firebase instead of heroku, see below:

![image](https://user-images.githubusercontent.com/20382062/79484346-68d4e600-800b-11ea-977c-de2f44b678d0.png)

Steps to repro:
1. Hit the hompage (https://resilience-app.herokuapp.com/)
2. Hit sign in
3. Hit sign in with google
4. Observe the dialog that appears and compare it to the domain the application is hosted on

Expected:
Domains match

Actual:
Domains don't match, end user may think they are granting access to a 3rd party site

**Comment by jwu910** [comment]
Suggestions on this? Apps hosted on heroku. Identity management is through firebase... would a custom domain for the app help solve this?
