### ISSUE TITLE
User cannot recover from "this number has been used to many times" error

### ISSUE THREAD

**Issue by nullHappy** [factn/resilience-app#256]
(This is possibly an enhancement rather than a bug)

I've logged in using just my phone number 3 times
On the 4th attempt I get a pop up that says I've used the phone number too many times

Screenshot: (I edited out my phone number)
![image](https://user-images.githubusercontent.com/20382062/79485017-78086380-800c-11ea-8290-3bb50fc7b28b.png)

The end user might find it helpful if they got information on how to resolve the issue and recover their account

Steps to repro:
1. Sign up using only your phone number
2. Enter the code and log in
3. Sign out and repeat step 2 twice more
4. Attempt to log in a fourth time using just your phone number

Expected:
User is able to log in. 
(Or user receives information on how to recover from this state)

Actual:
User receives a popup informing them they've used the phone number too many times

**Comment by mat10tng** [comment]
this is expected behavior
