### ISSUE TITLE
[Bug] Profile photo cropping not aligned

### ISSUE THREAD

**Issue by jwu910** [factn/resilience-app#262]
**Expected**
As a user changing my profile, I expect the image within the crop circle to be my new photo

**Actual**
The photo saved is not what is within the cropping circle

![image](https://user-images.githubusercontent.com/12107969/79585480-b6416980-8084-11ea-9d0e-ad3f8aae06b3.png)

![image](https://user-images.githubusercontent.com/12107969/79585534-cd805700-8084-11ea-9fb5-b6e77c084cf8.png)

**Comment by marekdano** [comment]
I'm sorry @JakeG-9191, I've just found that this issue was assigned to you. I've just done PR for fixing it.

**Comment by JakeG-9191** [comment]
> I'm sorry @JakeG-9191, I've just found that this issue was assigned to you. I've just done PR for fixing it.

Marek no problem at all, I had not fully fixed it so I am glad you took it over, I'll look over the PR now
