### ISSUE TITLE
Favicon.ico loads every time the route changes

### ISSUE THREAD

**Issue by qdozaq** [factn/resilience-app#272]
This should only need to be requested on the initial site load. Don't know why it's being requested every time the route changes.

![image](https://user-images.githubusercontent.com/20975817/79639889-67670300-815c-11ea-983d-5a4003865b5f.png)

**Comment by DrewThomasCorps** [comment]
From everything I've read, this appears to be a chrome bug, however I was playing around with the manifest.json (and actually updated the link to grab the right favicon) and now it only makes the request on new pages, and I can't get it to make more requests when visiting pages again after the initial load. (I'll submit a PR)
