### ISSUE TITLE
Optimization: Typography and Font styles are written many times almost exactly the same

### ISSUE THREAD

**Issue by jwu910** [factn/resilience-app#276]
Typography and font styles is an area to optimize some code that seems to be written many times (wet).

Some optimizations can be made as referenced below:

https://github.com/factn/resilience-app/pull/267#pullrequestreview-395928293

https://github.com/factn/resilience-app/pull/267#discussion_r410718719

**Comment by CSumm** [comment]
Is anyone assigned to this currently? I can tackle it

**Comment by CSumm** [comment]
@jwu910 I'm looking to enhacing the typography.jsx file and they suggest in the material-ui docs variant-mapping: https://material-ui.com/components/typography/#changing-the-semantic-element

Is this something we would like to do? If so, I can put the PR in.

**Comment by CSumm** [comment]
@jwu910  if you have time, would it be possible to pair code through this one?
