### ISSUE TITLE
Cleanup logic around Signup

### ISSUE THREAD

**Issue by Eihcir0** [factn/resilience-app#290]
In an effort to get out mvp0 we are postponing work on certain cleanup and edge cases around the **signup flow**.   This ticket is for tracking those items:

**Known issues**:
 - Currently, we require phone auth as the first step in the Signup process.  This creates a user with a uid on Firebase which we retain and use in the final step of the Signup process when we update the user profile with info they've entered on the form.   However, there is a second optional step, **Connect social media,** which _also creates a new user on firebase_ with a different uid.  We are currently ignoring this second uid but retaining the email/name to populate the volunteer form.   We need to clean up this logic so that a new uid is not created and they are all linked together.  [These docs should help](https://firebase.google.com/docs/auth/web/account-linking)

 - Missing front end form validation on the user profile page

 - Missing server error handling

 - Missing tests

 - We should revisit the User schema including required fields, field types, etc.  Certain fields were added/altered at the last minute to make mvp0 (`description`, `volunteerDetails.availabilty`, `email`, `phone`)
 
 - Revisit form fields on signup, such as email.  For now we do not ask user for email but if they link social media we retain that.  Also we are currently not handling profile picture in this flow.

**Flows/edge cases to handle**:
1) What happens if a user does a normal login (with social media/phone) and it is determined that this is a new user?
2) Normal login and we find an existing user but their UserProfile hasn't been updated and/or social media not connected (perhaps as a result of  bad data in the db coming from the comments above)?
3) What happens if a user is going through signup and an existing user with same phone is found?
4) What if during signup the the initial phone number isn't found but other existing user account(s) with same email are found?

**Comment by azmainamin** [comment]
@Eihcir0  I can try to answer:
#1 If its a new user, we show a dialog saying their account was created and then take them to their home page.
3# While signing up phone OR email( Google/FB), if there is another user with the same cred, we ask them to login with that cred. Basically, for 1 phone number and 1 email, we allow only 1 user.
#4 I believe the above answers these questions.
