### ISSUE TITLE
Create Mission "Helper" field should read "Name / phone number"

### ISSUE THREAD

**Issue by laredotornado** [factn/resilience-app#292]
Currently label reads, "Handle / phone number"

<img width="584" alt="Screen Shot 2020-04-20 at 9 13 19 PM" src="https://user-images.githubusercontent.com/14842313/79817820-e8382180-834b-11ea-90f1-fd72d67e48b7.png">

**Comment by ShanuCreations** [comment]
@azmainamin - I'll take this up. Could you please assign this issue to me ?

**Comment by ShanuCreations** [comment]
@laredotornado / @azmainamin - I've changed the label for 'Helper' locally. Here is the screenshot attached. 
![Helper-Label Changed](https://user-images.githubusercontent.com/62701681/79858289-1870d600-83c7-11ea-95a5-f4d47b9f3fef.JPG)

**Comment by ShanuCreations** [comment]
@laredotornado / @azmainamin - I've changed the label for 'Helper' locally. Here is the screenshot attached. 
![Helper with Amended Label](https://user-images.githubusercontent.com/62701681/79858692-b6fd3700-83c7-11ea-8c49-78c2e6598f35.JPG)

**Comment by ShanuCreations** [comment]
@laredotornado / @azmainamin  - It seems to be an issue with Recipient's label too, would you like me to change that as well whilst I'm on that page?

**Comment by azmainamin** [comment]
@ShanuCreations Yes...the recipient label should read the same. Thanks!

**Comment by utunga** [comment]
Thanks @dyanawu
