### ISSUE TITLE
Required fields on create mission page do not contain an "*"

### ISSUE THREAD

**Issue by laredotornado** [factn/resilience-app#298]
When someone creates a mission, all fields (except the photo) are required.  However, not all fields have an "*".  For example, notice that the "Mission title" has a "*" but the "Add a recipient" does not ...

<img width="577" alt="Screen Shot 2020-04-21 at 9 38 10 AM" src="https://user-images.githubusercontent.com/14842313/79882933-ece6ef00-83b8-11ea-9f19-9dc252035f2d.png">

This is true as well before someone enters text in the field, the placeholder text boxes do not consistently contain the required "*" characters ...

<img width="589" alt="Screen Shot 2020-04-21 at 9 37 44 AM" src="https://user-images.githubusercontent.com/14842313/79883052-0f790800-83b9-11ea-9410-3a14b067241c.png">

**Comment by ShanuCreations** [comment]
@laredotornado - I've fixed this locally as attached screenshot. However, just wondering, if this is required for 'Pickup' and 'Dropoff' location too as can't find a way to apply it using AlgoliaPlaces API ? Trying to figure out a way forward....

![New Mission Mandatory Fields](https://user-images.githubusercontent.com/62701681/79891584-1a538d00-83f9-11ea-8e63-904b30b75ee1.JPG)

**Comment by laredotornado** [comment]
@ShanuCreations , It took me FOREVER to figure out how to get a valid drop off and pickup.  For some reason, it only takes cities and states at the moment.  So, "Chicago, Illinois, United States of America" will validate.  

Also, I've just been told by @utunga that field labeled "Helper" is not required, so it doesn't need an asterisk.

**Comment by ShanuCreations** [comment]
@laredotornado , Thanks for your response ! Does that mean 'Drop-off' and 'Pickup' doesn't require asterisk, could you please confirm ?  Sure, I'll remove asterisk for Helper field.

**Comment by qdozaq** [comment]
I believe @Eihcir0 found that the location api was set to only use cities. Not sure if a PR went in to change that though

**Comment by Eihcir0** [comment]
I didn't put a pr in for that yet.  The fix is to delete the line that says:
```
  type: "city"
```
in `src/appcomponent/AddressInput/AddressInput.jsx'

**Comment by dyanawu** [comment]
@Eihcir0 I see the fix you mentioned is already in #311 but that option still exists in `src/app/page/MissionCreate/MissionForm.js` (and only there). Would it make sense to remove it there also? If so, I'll submit a PR for that.

**Comment by utunga** [comment]
Thanks for the PR @dyanawu
