### ISSUE TITLE
Address icon should not be a hand cursor (imply clickability)

### ISSUE THREAD

**Issue by laredotornado** [factn/resilience-app#300]
When creating a mission, the pickup and dropoff address location fields show an address icon to the far right of the text field, in which the cursor turns into a hand (implying the ability to click the icon) when hovering above that icon

<img width="572" alt="Screen Shot 2020-04-21 at 10 42 07 AM" src="https://user-images.githubusercontent.com/14842313/79897629-9b962a00-83cf-11ea-9324-8f6a96b1f8ca.png">

The icon is not clickable and the cursor should not change when hovering above.

**Comment by mzeenkala23** [comment]
I would like to take this as its simple enough to fix, especially with my schedule

**Comment by mzeenkala23** [comment]
I have fixed this locally on my machine. Do I need permissions to move forward or I can just send a pull request?

**Comment by dyanawu** [comment]
I was trying to reproduce, and the icon _is_ clickable and does something:

![image](https://user-images.githubusercontent.com/41310948/80187388-23836a80-8642-11ea-8eaf-7aa3a9e7a7fc.png)

**Comment by jwu910** [comment]
Hey @dyanawu I was working on another ticket and came across this too.

The button requests access to your browsers location, but after that does nothing. I think the expected behavior would have been something like opening a map to pick a location on a map. But because that isn't implemented, we should have the hover and click listeners disabled.

**Comment by jwu910** [comment]
@mzeenkala23 just send a pull request from your fork.

**Comment by dyanawu** [comment]
> Hey @dyanawu I was working on another ticket and came across this too.
> 
> The button requests access to your browsers location, but after that does nothing. I think the expected behavior would have been something like opening a map to pick a location on a map. But because that isn't implemented, we should have the hover and click listeners disabled.

Fair, I suppose if we're not using that functionality :)

**Comment by jwu910** [comment]
Feel free to shoot a PR over if you have a fix too. @dyanawu

**Comment by marekdano** [comment]
Is someone working on this issue? If not, I'm free to take it.

**Comment by marekdano** [comment]
I've checked the issue on the current master and compared it with the [algolia example](https://community.algolia.com/places/examples.html#link-to-a-map). The "hand" is displayed there too and when you clicked on it, there is no "action" before the location has been allowed/locked on the browser.

**Comment by jwu910** [comment]
@marekdano I think the original issue is trying to say that because clicking it does nothing (unless theres some implementation detail we have missed), then we should change the cursor style to not pointer until the functionality is as expected.

Having a pointer cursor indicates that an element is clickable.

**Comment by marekdano** [comment]
@jwu910 I think the change has to be done at the `algolia-places-react` library level.

**Comment by jwu910** [comment]
> @jwu910 Then I think the change has to be done at the `algolia-places-react` library level.  

We should be able to just grab the class on the element and force an override style if the Algolia api doesn’t offer it

**Comment by DrewThomasCorps** [comment]
I've looked into this, it appears that the button is supposed to find your current location and fill it in. I'm going to look into why it's not doing that.

**Comment by DrewThomasCorps** [comment]
https://discourse.algolia.com/t/algolia-places-usedevicelocation-or-default-location/3798/6
They recognized the issue, but didn't actually fix it. You can see it's a problem on their homepage: https://community.algolia.com/places/

**Comment by DrewThomasCorps** [comment]
https://github.com/algolia/places/issues/952
So this is actually the intended behavior, but since we don't do anything with the geolocation I'll work on removing it.
