### ISSUE TITLE
When creating a mission, back-end shouldn't force "Helper" field to be required

### ISSUE THREAD

**Issue by laredotornado** [factn/resilience-app#302]
Currently when you create a mission, you are forced to fill out all fields (except photo).  Failing to fill out all fields causes validation to fail when you click "Create Mission".  However, "Helper" should not be required

<img width="591" alt="Screen Shot 2020-04-21 at 7 47 43 PM" src="https://user-images.githubusercontent.com/14842313/79928668-2a736880-8409-11ea-96b9-bc78cefaf204.png">

**Comment by ShanuCreations** [comment]
@laredotornado  - I'll take this up as I think I figured out a way to fix this. Could you please assign this to me ?

**Comment by azmainamin** [comment]
@ShanuCreations assigned!
