### ISSUE TITLE
npm list returns a bunch of warnings about missing peer dependencies

### ISSUE THREAD

**Issue by utunga** [factn/resilience-app#314]
```npm list``` after a clean npm ci does this..,

![image](https://user-images.githubusercontent.com/166867/80185252-268d5380-8660-11ea-9205-a0789049e0fd.png)

**Comment by qdozaq** [comment]
The better-docs one is really annoying cause that module just did their peer-dependencies wrong. I'm not sure we even need it, pretty sure no one is using the generated docs.

Same thing with `mui-datatables` they have their peer deps set to version 3 while we're on version 4. (looks like they're still on their way to full support for v4 so this one we'll just have to deal with for now)

We're not even using sass. we should get rid of `sass-loader`

**Comment by mat10tng** [comment]
lets remove the better docs and sass-loader ?

**Comment by jwu910** [comment]
sass-loader might already be bundled with create-react-app. May not need it in the package.json, but it will probably still show up in our package-lock/node_modules after installs.

MUI 4 came out about a year ago. Hopefully enough time to have all/most of their modules upgraded as well.

We might just want to keep an eye on the versions we have installed with all the active development with MUI.
