### ISSUE TITLE
Algolia key is not happy - breaks address autocomplete

### ISSUE THREAD

**Issue by utunga** [factn/resilience-app#316]
![image](https://user-images.githubusercontent.com/166867/80210172-69165680-8687-11ea-8dfa-789c7951588f.png)

@laredotornado any ideas about this ? Sorry about the mess with keys btw still waiting to hear back from people its getting a bit critical....

**Comment by azmainamin** [comment]
@jwu910  We can close this now, right?

**Comment by jwu910** [comment]
Yeah this shouldn't be an issue. Everyone should have their API keys set up locally to use the algolia search.
