### ISSUE TITLE
2 Tests are failing on our current build.

### ISSUE THREAD

**Issue by thirdeyeclub** [factn/resilience-app#323]
Logs:
**2020-04-25T23:17:15.5456807Z** FAIL src/app/page/Home/Home.test.js
**2020-04-25T23:17:15.5459594Z**     Firebase instance does not yet exist. Check your compose function.
**2020-04-25T23:17:15.8682020Z** FAIL src/app/layout/Appbar/Appbar.test.js
**2020-04-25T23:17:15.8704979Z**     Found multiple elements with the role "navigation"

**Comment by thirdeyeclub** [comment]
@ commit # 412

**Comment by qdozaq** [comment]
Looking into this
