### ISSUE TITLE
Join our slack invitation link is no longer active

### ISSUE THREAD

**Issue by mattwr18** [factn/resilience-app#332]
The [join our slack](https://bit.ly/join_mutualaid_slack) link leads to an invitation is no longer active page. One can create an account if they have a @uww.edu email, but not if they do not.

![Screenshot from 2020-04-27 15-09-33](https://user-images.githubusercontent.com/26943915/80375881-43609b80-8899-11ea-9f53-74a01fb4a79b.png)

Can the invitation be refreshed, or how else can one join the slack workspace?

**Comment by utunga** [comment]
Thanks for the note. I need to update the link. As it expires every so often.. woops! 

Fortunately i made it a rebrandly link so I can update it in one place and it changes everywhere.

But wait, you seem to have found the old https://bit.ly/join_mutualaid_slack link.. thought I had tracked down all the places with that - can you tell me please what you clicked on / what page you were on when you clicked on 'join our slack' so we can update that one also?

**Comment by mattwr18** [comment]
Yes @utunga , I was on the CONTRIBUTING.md page

**Comment by utunga** [comment]
Found it - just waiting on the above PR to merge. (Weird I coulda sworn I fixed this already maybe the PR never got approved)

**Comment by mattwr18** [comment]
thanks a lot @utunga ... I'm in the slack instance now as @Matt Rider
