### ISSUE TITLE
[BUG] Success message is missing when user updates profile on user profile page

### ISSUE THREAD

**Issue by CSumm** [factn/resilience-app#344]
1. Go to app using localhost or the Heroku development app
2. Sign up or sign into app whichever way
3. Open up navigation sidebar and go click on user profile.
4. Make a change to display name or add an image
5. Observe result once change is made

Expected result: Success message appears when editable item inside of user profile is changed.

Actual result: Success message is missing when an editable item is changed inside of user profile.

Relates to Airtable card 75: https://airtable.com/tblRjd2McKgRW9MKj/viwlRRNI0PZIxrGkc/recqdAylRmM3FwpAJ?blocks=hide

**Comment by ShanuCreations** [comment]
@CSumm - I'll take this up. Could you please assign this to me ?

**Comment by ShanuCreations** [comment]
@CSumm - I've created a Snackbar message on successful profile save, does this text look OK ?

Let me know if it needs any amends and following that I'll create a PR.

![Profile Save Success Message](https://user-images.githubusercontent.com/62701681/80520387-41720780-8981-11ea-9a0a-38fa349e090c.JPG)

**Comment by CSumm** [comment]
Looks good to me
