### ISSUE TITLE
Interactivity on the map to let organizer click from map to list

### ISSUE THREAD

**Issue by DAHuerta** [factn/resilience-app#366]
**Description**

As an organizer, there is some interactivity on the map to let me click from a mission on the map to see it in the list or from the list to the map.

[Airtable #168](https://airtable.com/tblRjd2McKgRW9MKj/viwlRRNI0PZIxrGkc/recw3OuQze4Zywts6?blocks=hide)

**Comment by andreagaietto** [comment]
Verified that all four tabs of missions control (proposed, planning, in progress, and done) are properly interactive and focusing on the correct items, as well as displaying the correct information, when clicking on the map as an organizer. I am closing this item.
