### ISSUE TITLE
ASAP or 'current' non-started missions are highlighted to grab organizers attention.

### ISSUE THREAD

**Issue by DAHuerta** [factn/resilience-app#367]
**Description**

As an organizer, any non-started missions with an ASAP or 'current' delivery window are highlighted on the planning view for my immediate attention so I can pay attention to these.

[Airtable #170](https://airtable.com/tblRjd2McKgRW9MKj/viwlRRNI0PZIxrGkc/recXIxRcwuimuzSIx?blocks=hide)

[Figma](https://www.figma.com/file/v5HdxDsvO2NzMuZU6CArzF/Resilience-App?node-id=3739%3A9164)

**Comment by mat10tng** [comment]
We will add this back once it in the roadmap
