### ISSUE TITLE
404 is displayed for broken links

### ISSUE THREAD

**Issue by DAHuerta** [factn/resilience-app#377]
**Description**

As a user, when I go to a broken link/page I see a quirky 404 system error page. (404/500/ etc pages).

Currently, it's just a basic page that says "Oops! That page cannot be found."

[Airtable #185](https://airtable.com/tblRjd2McKgRW9MKj/viwlRRNI0PZIxrGkc/recwe4ashPrrR98fZ?blocks=hide)

**Comment by mat10tng** [comment]
This is done
