### ISSUE TITLE
Volunteers can not start a missions that are not labeled 'ready to start'

### ISSUE THREAD

**Issue by DAHuerta** [factn/resilience-app#393]
![mission_states.png](https://images.zenhubusercontent.com/5ea20d02b3851009106d74e7/3ca3b0fe-7dd9-4c94-b6a1-e87faf68f123)[Uploading... mission_states.png ]

**Description**

As a volunteer, I can't start missions that are not  'ready to start' (and both volunteer and organizer understand why this is), so that organizer can be sure that missions have been 'paid for' or otherwise arranged with any third parties before the volunteer starts to do them.

[Airtable #149](https://airtable.com/tblRjd2McKgRW9MKj/viwlRRNI0PZIxrGkc/recAOHQ9a3IfGnnUA?blocks=hide)

**Comment by mat10tng** [comment]
This is ready in design, and also implemented, QA ?

**Comment by utunga** [comment]
This is not a design issue - its implemented and completed. Closing ...
