### ISSUE TITLE
Setup automated test before commit, push

### ISSUE THREAD

**Issue by mat10tng** [factn/resilience-app#40]
We have now Husky which will do automated linter each time we commit
https://github.com/typicode/husky

I would like to have also automated test each time we commit + push as well

**Comment by CSumm** [comment]
CircleCI a good tool. It requires admin access to install however

**Comment by mat10tng** [comment]
Yeah, I think we can just make sure that the tests are running in local before it is pushed into the branch? 
// package.json
{
  "husky": {
    "hooks": {
      "pre-commit": "npm test",
      "pre-push": "npm test",
      "...": "..."
    }
  }
}

**Comment by Raf-Batista** [comment]
Based on what I found I think we can do something like this. 

// package.json
"husky": {
  "hooks": {
    "pre-commit": "npm run lint && npm test",
    "pre-push": "npm run lint && npm test"
  }
}

I'll do some more reading into Husky
