### ISSUE TITLE
Need a better input component for phone numbers

### ISSUE THREAD

**Issue by qdozaq** [factn/resilience-app#414]
Firebase only accepts the format `+1xxxxxxxxxx` but it's not super clear that thats how the number should be entered.
Would be nice to have a component that lets you select that country code and specify your number separately and then format everything behind the scenes

**Comment by utunga** [comment]
Seems like this is a dupe/related to 
https://github.com/factn/resilience-app/issues/351

**Comment by jwu910** [comment]
Still separate, @utunga this sounds like the actual input element with a country code dropdown  with some validation.

#351 sounds like positioning and flow?

**Comment by qdozaq** [comment]
@utunga hmm yeh i guess this is pretty similar.

@jwu910 Maybe we should just update the other one to explicitly say this component needs to be created?

**Comment by marekdano** [comment]
I can take this issue. My plan is to replace text input of phone number by the firebase pop-up as it was suggested in #351 if it's OK.
