### ISSUE TITLE
Organizers can see all the missions on a map

### ISSUE THREAD

**Issue by DAHuerta** [factn/resilience-app#423]
**Description**

As an organizer, when I'm looking at a given tab in mission control I can see all the missions on a map, so I can understand their relative positions and group them.

[Airtable #167](https://airtable.com/tblRjd2McKgRW9MKj/viwlRRNI0PZIxrGkc/recGt0Qb1EWCaUHLl?blocks=hide)

**Comment by mat10tng** [comment]
done
