### ISSUE TITLE
Organizers can mark a delivery as failed

### ISSUE THREAD

**Issue by DAHuerta** [factn/resilience-app#424]
**Description**

As an organizer, if a mission is having problems or gone too long without delivery I can mark it as 'failed' so that it is no longer in the 'in progress' view.

**Airtable Reference**
[Airtable #178](https://airtable.com/tblRjd2McKgRW9MKj/viwlRRNI0PZIxrGkc/recqWV8pd0ntBz6og?blocks=hide)

**Design**
[Figma](https://www.figma.com/file/v5HdxDsvO2NzMuZU6CArzF/Resilience-App?node-id=4417%3A11099)

**Comment by andreagaietto** [comment]
Closing; things are moving over to the Done section and being marked as failed correctly. Also being reflected as failed in the .csv.
