### ISSUE TITLE
Organizers can see missions that have started in mission control

### ISSUE THREAD

**Issue by DAHuerta** [factn/resilience-app#442]
**Description**

As an organizer, on mission control “In Progress” view, I want to see missions that have STARTED.

As an organizer, I don’t want to see a giant map on the screen as I mainly want to see the list missions and their statuses.

[Airtable #221](https://airtable.com/tblRjd2McKgRW9MKj/viwlRRNI0PZIxrGkc/recDMtXib3T5zfAtQ?blocks=hide)

**Comment by mat10tng** [comment]
this is done
