### ISSUE TITLE
Organizers can fund missions in mission control 'Proposed' view

### ISSUE THREAD

**Issue by DAHuerta** [factn/resilience-app#449]
**Description**

As an organizer, mission control "Proposed" view allows me to prepare missions for volunteers by "funding" each mission

[Airtable #118](https://airtable.com/tblRjd2McKgRW9MKj/viwlRRNI0PZIxrGkc/rec2sgm2CLd5QrNca?blocks=hide)

[Figma](https://www.figma.com/file/v5HdxDsvO2NzMuZU6CArzF/Resilience-App?node-id=3439%3A5500)

**Comment by mat10tng** [comment]
this is done?

**Comment by jwu910** [comment]
@mat10tng Talked to @DAHuerta about starting to migrate tickets from airtable over. Airtable doesn't seem to have updates if tickets are closed or not (or i don't see it)

This ticket didn't have an attached PR. so if this is done, lets find that PR and we can close this.

**Comment by dyanawu** [comment]
@jwu910 This is among the airtable cards I was mentioning. Linked a PR that fixes the only issue I found while testing it.

The original implementation was in PR #309 

I think this can be closed.

**Comment by jwu910** [comment]
If this has been QA'd and verified to be working on master, i think we're good to close.

**Comment by dyanawu** [comment]
Sorry @utunga I forgot to ask you to hold off closing while I ran one last QA:

Mission titles now show up as 'resource' on all missions and I suppose this might be due to the introduction of multiple boxes per mission:
![image](https://user-images.githubusercontent.com/41310948/82154490-f2910100-98a0-11ea-9917-af2ff63b29ad.png)

Issue #555 filed

**Comment by jwu910** [comment]
Is the original acceptance criteria of this completed? If there is something like "resource" being the title, i think the new issue you've opened up #555 is out of scope of this and we can close this.

**Comment by dyanawu** [comment]
Okay, agreed and original criteria (somewhat nebulously come up with) is fine.
