### ISSUE TITLE
Success message is presented after successfully updating profile/account

### ISSUE THREAD

**Issue by DAHuerta** [factn/resilience-app#450]
**Description**

As a user, I can see a success message when I update my profile/account so that I know it succeeded.

[Airtable #75](https://airtable.com/tblRjd2McKgRW9MKj/viwlRRNI0PZIxrGkc/recqdAylRmM3FwpAJ?blocks=hide)

**Comment by jwu910** [comment]
https://github.com/factn/resilience-app/issues/344

Should be closed by this

**Comment by jwu910** [comment]
Let's verify on the demo that this feature works, and lets close this out. 

Airtable ticket should be closed as well. looks like it wasn't workflowed

**Comment by CSumm** [comment]
The data that is changed is not persistent with app refreshes. Will put in issue relating to this

**Comment by jwu910** [comment]
@CSumm can you be more detailed with what you mean by that?

**Comment by CSumm** [comment]
When changing phone number, the success message appears, but on page reload, none of the changes exist. I wrote a ticket that extends @marekdano's bug with a completely void user profile

**Comment by mat10tng** [comment]
this is done, request another QA

**Comment by andreagaietto** [comment]
@utunga @mat10tng I tested this out and was successfully able to update my phone number and have it stick after logging out/logging back in.
