### ISSUE TITLE
Developers can easily reuse custom icons

### ISSUE THREAD

**Issue by amylo** [factn/resilience-app#458]
We don’t have reusable UI components for our custom icons, eg. folks are referencing the apple.svg icon directly from within their views…
We should create UI components for each of our custom icons and put them under /src/app/components/icons  and update the existing views to use those. 

Benefits:
1. Easily reuse icons with other components as React components
2. Developers can find all icons in one place as ready-to-use React components
2. Easily align all icon properties and sizes

**Comment by thirdeyeclub** [comment]
I understand this s a good idea for icons we dont have in material UI. So far everything I have worked on has used icons from Material UI including the apple svg found at '@material-ui/icons/Apple';

**Comment by jwu910** [comment]
The MUI Apple icon isn’t the same as what the designers are asking for. The icon there I think is the Apple logo icon
