### ISSUE TITLE
Type string does not match type .. for key fundedDate

### ISSUE THREAD

**Issue by utunga** [factn/resilience-app#459]
Running localhost/master branch I was on this page:
![image](https://user-images.githubusercontent.com/166867/81050848-d8583a00-8f14-11ea-903b-cd24593ecd1a.png)

And chose 'funded by donation' then it did this...
![image](https://user-images.githubusercontent.com/166867/81050824-c9718780-8f14-11ea-8070-9f94714cfa25.png)

Just old data? Or ?

**Comment by mat10tng** [comment]
hmmm, I saw that too, this is because of how our default data define to null, which default to object instead of empty string, but in schema.ts we did say that it could be both string or null, but that is not how the rSanitize function work
