### ISSUE TITLE
Unfriendly error if you don't format your ph number correctly when asking for a box

### ISSUE THREAD

**Issue by utunga** [factn/resilience-app#467]
![image](https://user-images.githubusercontent.com/166867/81174705-6a843f00-8ff6-11ea-8772-776a72b04a90.png)

Being a programmer I read this error message and realised there was something wrong with the format of the phone number.

Most users will just see the red and gobbledygook and assume something is broken.

**Comment by utunga** [comment]
I'm gonna put this here also because it probably relates.

Next step after this was..
![image](https://user-images.githubusercontent.com/166867/81174932-cc44a900-8ff6-11ea-818e-c5e3da8d8a4a.png)

**Comment by mat10tng** [comment]
@qdozaq  maybe ? I am sure he know more about this

**Comment by qdozaq** [comment]
I can put in some friendlier messages

**Comment by utunga** [comment]
BTW based on the console I saw that second error pops up again when something went wrong with the recaptcha widget. TBF no idea why the Recaptcha widget wasn't loading - it may just have been a bad internet connection on my part.

**Comment by jwu910** [comment]
Can grab that error and pass it into the `snackbarContext.show` method with `error.message` as the `message` prop
