### ISSUE TITLE
We need a better address picker

### ISSUE THREAD

**Issue by utunga** [factn/resilience-app#471]
In this [comment on a pr](https://github.com/factn/resilience-app/issues/387#issuecomment-623263341) we talked about the three places we use maps in the app.

Specifically
- Organizer dashboard
- Volunteer dashboard (mostly trying to defer to Google Maps)
- Address pickers (for user profile and setting mission pickup/drop off locations). 

Last night, about 1 am, in trying to get the google maps thing to work I had a sinking realization that we have a pretty major usability problem with the address picker.

We have the Algolia address picker, but I am concerned that as currently, the Algolia method for typing and geolocating addresses is going to have a lot of problems. I suggest you go ahead and try it on the [Request Foodbox](https://resilience-app.herokuapp.com/request/foodbox) interface.

The UI looks sweet by the way! But if you try to enter real actual addresses you encounter lots of problems (or at least I did). I'm worried we're going to end up with lots of badly entered addresses and (worse) people not being able to correctly pick up or deliver parcels. 

I already filed #468 about the specific problem of not being able to enter apartment number but I think we're going to have worse problems than that. 

For instance, if trying to enter "Unit 3, 123 Coldwater Canyon,  CA 91423" the Algolia picker does this:

![image](https://user-images.githubusercontent.com/166867/81248820-5c273900-9071-11ea-9981-0f9366493f41.png)

By contrast, the google picker is not much better - it does this:
![image](https://user-images.githubusercontent.com/166867/81248924-95f83f80-9071-11ea-9788-c81f137c297a.png)

In either case, the end-user needs to know that they need to reformat their address until it is actually parsed correctly by the geolocation API. 

Like this:
![image](https://user-images.githubusercontent.com/166867/81249082-e7083380-9071-11ea-9025-43049d801504.png)

But getting them to actually do this correctly is vital. Firstly, so that our volunteers don't get confused. And secondly, we need that nicely formed address so that - when we fire the address back at Google Maps for the turn by turn directions - Google Maps is actually able to actually render the location/route. 

--

I did a bit of research on this and from a UX perspective, the Uber location picker is considered one of the best out there. What's super cool is, after you enter the address, you can then use zoom and pan to drag the pin to put the pin in the exact right location..

![image](https://user-images.githubusercontent.com/166867/81249187-259dee00-9072-11ea-9a46-bdf2f76dd20b.png)

Being able to fine-tune like Uber is probably an MVP1 type feature but as an interim feature, I think we really need to pair these address fields with a map just under, or above the address, so that they can get a preview of where they mean.

That is, we don't want to just show them that Algolia or Googlemaps was *able* to parse the address but that it was able to parse it to *this specific address* - thus giving the user time to correct it if its gonna be in the wrong place. 

My current thought is we have something like:
+-------------+
|      map        |
+-------------+
[address input]
[address detail]

So they can update the address input and the map preview updates in real time, and then directly under that a second input for putting stuff like 'Unit 2' or '(NOHO Police Station)' Or whatever. That would solve  #468 at the same time.

What do folks think? Can we do a general-purpose component for this? Maybe react-leaflet-location-picker is all we need? Or is it just a good start?

Thanks! 

--

PS
The address detail field would be for stuff specifically relating to the address (such as "Unit 2"). Other directions (such as "please press the buzzer and wait for the super, the dog has COVID and Rabies so whatever you do don't open the gate' ) would go into the actual mission notes....

**Comment by sahjoo** [comment]
Maybe this is a quick solve for saving accurate addresses for now..
Could we force the user to only get an address inputed into the form if they select one of the listed options that comes up in the search? grubhub and doordash does this (I personally find this annoying only because my address isn't on google maps, so i have no choice but to choose our nearby rental office address. But I'm probably an edge case).

**Comment by mat10tng** [comment]
But then the address and the lat+long are not really corresponding to each other, 
the way it works right now is that you pick an address -> this turn into lat, lng

Your suggestion:
address  -> lat, long -> map pin -> move the map pin to correct -> save ?
