### ISSUE TITLE
[BUG] Modified user profile data fails to persist after app reload when returning back to user profile page

### ISSUE THREAD

**Issue by CSumm** [factn/resilience-app#473]
1.  Enter [Heroku app](https://resilience-app.herokuapp.com/) and sign up as volunteer
2. Open side navigation and go to user profile
3. Change any field relating to user profile such as photo, city information, etc
4. Click on save changes
5. When app refreshes, go back to user profile page
6. Observe the user profile page

Expected result: 
Volunteers can see their profile changes as soon as the app refreshes on the user profile page

Actual result:
Changes to the user profile by volunteers appear to be erased after app refresh.

Additional notes: User can disconnect Google account from user profile, but cannot add it.
Relates to #460

**Comment by mat10tng** [comment]
This is fixed by https://github.com/factn/resilience-app/pull/463
