### ISSUE TITLE
Create failed mission button

### ISSUE THREAD

**Issue by DAHuerta** [factn/resilience-app#480]
**Specifications**

- Organizers should have a **button** to mark a delivery as **failed**.

**Comment by mat10tng** [comment]
this is done

**Comment by andreagaietto** [comment]
@mat10tng Once a mission is marked as failed, what is the expected behavior for the mission? Should it return to Planning, or just stay in Done, but marked as failed? Thanks.

**Comment by mat10tng** [comment]
it should move to done

**Comment by andreagaietto** [comment]
Thanks for confirming!
