### ISSUE TITLE
UI bug on volunteer dashboard mobile

### ISSUE THREAD

**Issue by qdozaq** [factn/resilience-app#507]
Seeing this when checking the site on an iphone both safari and chrome apps.

To test go here and sign in on mobile device: https://mutualaid-757f6.web.app/

appears to be an issue with grid/flex

![IMG_4150](https://user-images.githubusercontent.com/20975817/81626240-1e0b7b80-93c9-11ea-9f47-00da9be7dbd0.PNG)

**Comment by mat10tng** [comment]
I dont have an iphone to fix this.

**Comment by DrewThomasCorps** [comment]
I'm going to look into this. It's my first issue (ever) so if someone can fix it fast go ahead.

**Comment by qdozaq** [comment]
@DrewThomasCorps Awesome! I'll assign you to it.
If you have a mac it will probably be a lot easier to debug this issue via the xcode iphone emulator or you should be able to access the dev site via the IP/localhost on your computer through your phone
