### ISSUE TITLE
[BUG] app at https://mutualaid-757f6.web.app/ disappears on login

### ISSUE THREAD

**Issue by dyanawu** [factn/resilience-app#517]
Repro steps:
1. Visit https://mutualaid-757f6.web.app/ (current staging/QA app deployment)
2. Sign in via phone with either of the sample data number/verification codes

Expected result: Logged in to app
Actual result: App interface appears briefly, then disappears, and the below console errors appear:

![image](https://user-images.githubusercontent.com/41310948/81804900-83d44080-954c-11ea-8672-d9dfa11abc76.png)

![image](https://user-images.githubusercontent.com/41310948/81805024-b847fc80-954c-11ea-8bfb-a4a558d6b9f8.png)

**Comment by utunga** [comment]
FYI if you follow the link it tells you the same thing as when you run on localhost, namely 

![image](https://user-images.githubusercontent.com/166867/81809718-e857c580-9575-11ea-83cc-b675fb28cd5b.png)

**Comment by utunga** [comment]
@amylo realize you may not be available any time soon but just FYI I thought I'd tag you in on this one because I think its possibly something to do with the new unauthorized access or maybe the 404 pages. ..
