### ISSUE TITLE
[BUG] / [ui] Missions not requiring funding show up unfunded in Planning view

### ISSUE THREAD

**Issue by dyanawu** [factn/resilience-app#518]
Minor QA issue: marking a Proposed mission as 'Funding Not Required' moves it into Planning, but still marked 'Not Yet Funded'. While it's logical, it might be worth updating it to reflect 'Funding Not Required' when in Planning.

Proposed (I then selected Funding Not Required):
![image](https://user-images.githubusercontent.com/41310948/81805303-2ee4fa00-954d-11ea-9554-00b90652b22f.png)

Planning:
![image](https://user-images.githubusercontent.com/41310948/81805323-3c01e900-954d-11ea-9f24-e8b46f811ba4.png)

**Comment by mat10tng** [comment]
I think the mission details is not finished, that is why
