### ISSUE TITLE
User Incorrectly Redirected

### ISSUE THREAD

**Issue by JakeG-9191** [factn/resilience-app#525]
1. Open Mission Control Dashboard
2. Navigate to Missions
3. Notice that click into the body of any missions that fall within "Proposed" redirects user to a blank white page, a reload is currently required to return to the dashboard
4. Note that this issue was not experienced in other areas of Mission Control, such as missions that fall under "Planning", "In Progress" or "Done"

**Actual**
Clicking within the body of a Proposed mission redirects user to blank page

**Expected**
Nothing should happen while clicking within the body of these missions, similar to how other sections are broken up

![Issue-RedircectBlankPage.PNG](https://images.zenhubusercontent.com/5ebaf217f72f15c885cc6da1/d6680aec-6fc6-4cc3-8303-0055a889b7d1)

**Comment by jwu910** [comment]
@JakeG-9191 Are you familiar with the inspector tool on your browser? If you are, it would be incredibly helpful to list the top section of the stack trace for some quick debugging.

**Comment by JakeG-9191** [comment]
@jwu910 Hi Josh, thanks for pointing that out, as I hadn't seen the stack trace on other debugging tickets I did not include it, I will keep this in mind with any future QA

**Comment by DrewThomasCorps** [comment]
I am attempting to replicate this. Whenever I click a proposed mission it just moves the map for me. Is this still an issue? (Using chrome on Mac)

**Comment by JakeG-9191** [comment]
@DrewThomasCorps Which environment were you using? I neglected to mention it but at the time had been using the app in its form here https://mutualaid-757f6.web.app/dashboard, possible that newer PRs could have fixed it

**Comment by DrewThomasCorps** [comment]
I was using my local dev environment.

**Comment by DrewThomasCorps** [comment]
I've tried replicating it at https://mutualaid-757f6.web.app/dashboard/missions?view=inProposed but it appears to have been fixed. I'm gonna close the issue.
