### ISSUE TITLE
Clarification of reasons behind failure to post mission - wrong input for locations

### ISSUE THREAD

**Issue by JakeG-9191** [factn/resilience-app#526]
1. Navigate to Resilience Application
2. Navigate to Create Mission and enter data for new mission
3. Note that putting in the wrong address format returns a 'Unable to save mission: Wrong input', though it does not specify what the wrong input is, it may be more helpful for users to see that the failure is related directly to the wrong address format, updating message likely provides for better user experience
4. Note that if there are multiple conditions for producing failed input message, each would benefit from more refined fail depending on reason for failure

**Actual**
User sees message concerning invalid input when wrong address is entered into pickup or drop-off areas

**Expected / Desired**
User sees message concerning invalid input related directly to wrong address format for better user experience

![Issue-RedircectBlankPage.PNG](https://images.zenhubusercontent.com/5ebaf217f72f15c885cc6da1/55e090dd-dd0c-4a1b-82a0-acd3a075c85c)

**Comment by jwu910** [comment]
Hey @JakeG-9191 I saw there were a few tickets like this being created.

Are you creating issues for bugs?

**Comment by JakeG-9191** [comment]
@jwu910 I've opened issues for both bugs and UI items, is it intended that this ticketing should be done in another way?

**Comment by jwu910** [comment]
@JakeG-9191 Per our discussion on slack, let's keep the labels off until we've established what we're working with.

If there is a suggestion for a better experience for the user, we'll want to pop that question in on the appropriate slack channel or ping some designers to take a look. Before we create an issue and task some work. 

I think Github had started releasing(released) their discussions feature but I haven't read into that yet. If possible, we can just use those to start that discussion on github to take a open up those request for comments.

**Comment by JakeG-9191** [comment]
@jwu910 Hi Josh, thank you for pointing that out, this was completed before our conversation earlier and I had not gone in to make the changes. Initially I was only given direction to conduct QA by creating new issues, I had not realized this also meant I needed to track down individuals to take care of the particular issues, I'll keep this in mind as I continue to test the application

**Comment by jwu910** [comment]
Thanks! Yeah I think to the point of free issue creation, sure your suggestion makes sense, but if the designers hadn't been notified of any required changes to the UI, too, we're gonna start really deviating from the mockups.

Good to keep everyone in sync.

:+1:

**Comment by JakeG-9191** [comment]
Sounds good, I actually noticed that this exact issue was created into a ticket 7 days ago with no movement yet so I am going to close out this issue

**Comment by jwu910** [comment]
Cool, can you reference that here before you close?

**Comment by JakeG-9191** [comment]
Sure thing, issue #474 notes this same issue
