### ISSUE TITLE
Spelling Catch - Organizer Signup

### ISSUE THREAD

**Issue by JakeG-9191** [factn/resilience-app#527]
1. Navigate to new organizer signup - https://mutualaid-757f6.web.app/organizer/signup
2. Note spelling issue for 'interested', considering adding '?' at end of first line of text

Actual
'Intereset in become an organizer'

Expected / Requested
'Interested in become an organizer?'

![Issue-SpellingCheck1.PNG](https://images.zenhubusercontent.com/5ebaf217f72f15c885cc6da1/315ffd86-433d-439f-bbbd-4a43ec239e59)

**Comment by mat10tng** [comment]
this is closed by previous pr
