### ISSUE TITLE
In the volunteer  dashboard the whole title bar should be clickable

### ISSUE THREAD

**Issue by utunga** [factn/resilience-app#546]
Currently its possible to click the small <i> to bring up the detail view 
![image](https://user-images.githubusercontent.com/166867/82123064-62dd4b00-97eb-11ea-959f-762829cde674.png)

But per the Figma designs it **should** be possible to click the whole title bar to get to the same thing, namely this 
<img width="679" alt="image" src="https://user-images.githubusercontent.com/166867/82123085-856f6400-97eb-11ea-86cc-b704edf75268.png">

--

Also you should see the 'pointer' icon (ie the little hand) so that you know its clickable anywhere in the title bar area for each mission

--

Finally, not sure if part of this issue or not but gonna mention it here anyway.. this pop up needs to work on an actual mobile device I'm not sure what this apparently modal dialog box thing will do in the case of a mobile device... .

**Comment by andreagaietto** [comment]
I tested this out on a mobile device. I get a blank screen after tapping on the "i" button.

**Comment by andreagaietto** [comment]
I am also having difficulties confirming a delivery from a volunteer aspect due to the behavior of the pop up box (mobile, chrome browser). It was mentioned to me that concerns are mostly aligned with recipient experience on mobile so I have not reported this as a separate issue at this time, bu if anyone would like for me to break it out in more detail in a bug report, let me know.

**Comment by qdozaq** [comment]
I tested this on my iPhone and on an andriod emulator but was still getting the popup.
Someone else may need to look at this

**Comment by thirdeyeclub** [comment]
On it!

**Comment by thirdeyeclub** [comment]
On it!!

**Comment by thirdeyeclub** [comment]
Please keep this issue still open, I was able to fix the clickable title bar but I haven't been able to antiquity test mobile via my phone as my connection keeps timing out. What i did test i kept getting an org is null ERROR

**Comment by kimhluu** [comment]
Can I get assigned to this issue, please?

**Comment by utunga** [comment]
Eek. Absolutely. Just go ahead and assign yourself. You're welcome

**Comment by utunga** [comment]
Actually @kimhluu this one is pretty much sorted so I'm going to close it again. 

You can test the current version of the app by going to the staging site at 
https://mutualaid-757f6.web.app

On that site, you can register using the volunteer or organizer mobile account (per readme https://github.com/factn/resilience-app#test-data) 

Phone Number | Verification Code | User Role
7777777777 | 123456 | Organizer
2223334444 | 123456 | Volunteer

In my testing this one is all good.. but I would love to maybe chat about a good issue for you to jump into if you like. Ping me on slack perhaps
