### ISSUE TITLE
[BUG] Seeing JSON under submitted requests view

### ISSUE THREAD

**Issue by andreagaietto** [factn/resilience-app#547]
**Steps to reproduce:**
1. As a user, create a new request for a food box delivery.
2. Request funding assistance with the food box delivery during check out.
3. Submit request.
4. Return to the home page of app.
5. Select "my requests" from the right hand menu.
6. View submitted requests.

**Expected result:**
User should be able to view formatted details of their submitted requests.

**Actual Result:**
User is seeing raw JSON containing information about their request.

**Screenshot:**

![image](https://user-images.githubusercontent.com/59374165/82124195-7052f080-976b-11ea-8e8b-650ea58f71f9.png)

_I am not 100% certain if this is an area that is currently in development, or if this is a clear bug. If it is currently in development, it may be related to this [airtable issue](https://airtable.com/tblRjd2McKgRW9MKj/viwlRRNI0PZIxrGkc/recjXDKz6IM5cckq6). I did want to mention this, though, as it will make it difficult for a user to see detailed of their pending requests. _

**Comment by mat10tng** [comment]
this is because @qdozaq had to do other priority coming in this week, and the view for this got delayed

**Comment by andreagaietto** [comment]
Ok perfect, couldn't 100% tell if this was an actual issue or just something in development from airtable.

**Comment by andreagaietto** [comment]
@mat10tng If this is known I will just close.
