### ISSUE TITLE
Unable to open confirm delivery popup on mobile

### ISSUE THREAD

**Issue by andreagaietto** [factn/resilience-app#548]
**Description:**
When acting as a volunteer, I am unable to confirm delivery of a package on mobile (chrome), due to behavior of a pop up box. Tested on two different android phones running different versions of android.

**Steps to Reproduce:**
1. On a mobile phone, go to https://mutualaid-757f6.web.app/.
2. On the home page, select "In Progress" to navigate to an in progress mission.
3. Tap "Confirm Delivery".

**Expected Behavior:**
Secondary pop up should open, allowing the user to confirm delivery (see screenshot for example of pop up from desktop version):
![image](https://user-images.githubusercontent.com/59374165/82128016-b026d180-9785-11ea-99bb-589f64cc03b1.png)

**Actual Behavior:**
Tapping on the "Confirm Delivery" button causes screen to go blank on mobile, instead of seeing the popup as pictured above:
![Screenshot_20200516-150304_Chrome](https://user-images.githubusercontent.com/59374165/82128110-815d2b00-9786-11ea-9e5e-c12228acfc63.jpg)

**Comment by andreagaietto** [comment]
@DAHuerta 

This may also be related to what @utunga mentioned on [Issue# 546](https://github.com/factn/resilience-app/issues/546). When I try tapping the "i", about a quarter of the time I get the same behavior (blank screen).

**Comment by qdozaq** [comment]
I tested this on my iPhone and on an android emulator but was still getting the popup.
Someone else may need to look at this

**Comment by andreagaietto** [comment]
I was just playing around on my phones and retesting this, and it seems to be working properly now (at least on two different androids). Am considering closing unless anyone wants to keep this open?

**Comment by andreagaietto** [comment]
Closing as this looks great now on my end.
