### ISSUE TITLE
Second page of request/foodbox flow gives error

### ISSUE THREAD

**Issue by utunga** [factn/resilience-app#550]
**Description**

Blank screen second step of foodbox flow

**Steps to reproduce**

1. Go to staging https://mutualaid-757f6.web.app
2. Click on need help then foodbox
3. Choose quantity, say, 3, of one of the boxes 
4. Click Continue

**Actual behavior**

Get a totally blank screen with this error in the console 
![image](https://user-images.githubusercontent.com/166867/82132055-9cd04080-982f-11ea-98f9-929c04fa2051.png)

**Expected behavior**

See the address picker interface and all that good stuff

---

Assigning both Tuan and Paul to this as an FYI only

**Comment by utunga** [comment]
Sorry I didn't get a chance to figure this one out but I did figure out it seems to be that org.location is null on this line ...
https://github.com/factn/resilience-app/blob/97bdb6505f770587a02e44f022e83c709833eed4/src/app/page/Request/foodbox/DeliveryStep.jsx#L105 

The weird thing is org.location is not null in other contexts so maybe some weird async thing?

**Comment by qdozaq** [comment]
Fixed. Somehow the orgs location got switched to an array in the DB. Not sure how that would happen as the schema and data.py dont generate arrays.

**Comment by qdozaq** [comment]
Ah it got seeded form the data.json which was changed for some reason. creating a PR to change back
