### ISSUE TITLE
Mission title displays as 'resource' on all missions

### ISSUE THREAD

**Issue by dyanawu** [factn/resilience-app#555]
Repro: click 'View Mission Details' in on any mission card in dashboard:

![image](https://user-images.githubusercontent.com/41310948/82154540-3126bb80-98a1-11ea-83e6-f03cc66bec59.png)

**Comment by dyanawu** [comment]
@jwu910 @utunga

**Comment by jwu910** [comment]
https://github.com/factn/resilience-app/commit/6e2a6bbc173c492bc650339175de64f208c9e8c9

It was changed here,

Not sure if a Resource title was expected to be included to display or not.

**Comment by dyanawu** [comment]
Okay, I see - I think I might be able to work on this. Sef-assigning

**Comment by jwu910** [comment]
Yeah it’ll be good to double check what’s supposed to be displayed here.

Maybe confirm with design, haven’t checked if everything had been updated to match the food box -> resource language

**Comment by dyanawu** [comment]
The displayed title also seems to be caused by the changes in https://github.com/factn/resilience-app/commit/6e2a6bbc173c492bc650339175de64f208c9e8c9, so for now I'll make it display something like a placeholder, and keep working on it after this.
