### ISSUE TITLE
When the user (Recipient) is logged in, the Home page "/" shows the Volunteer’s mission dashboard

### ISSUE THREAD

**Issue by amylo** [factn/resilience-app#576]
When the user (Recipient) is logged in, the Home page "/" shows the Volunteer’s mission dashboard.  However this is the desired behavior if the user is Volunteer or Organizer.  The issue is that the Home page route is considered public and anyone can see it, but the current logic right now is that when the user is authenticated they will see Volunteer’s Home.

### Expected Outcome
On the authenticated Home page "/" for Recipients, they will be presented with "Coming soon" message.

### Actual Outcome
When the user (Recipient) is logged in, the Home page shows the Volunteer’s mission dashboard.

**Comment by karenkun** [comment]
Confirm it shows on https://studiocity.resilienceapp.org/
