### ISSUE TITLE
Trouble with referers on new domain 

### ISSUE THREAD

**Issue by utunga** [factn/resilience-app#581]
If anyone has ideas on this one it'd be appreciated

Steps to reproduce. 
1/ Go to  https://studiocity.resilienceapp.org
2/ Attempt to login 

![image](https://user-images.githubusercontent.com/166867/82278834-3ab63d80-99df-11ea-8ee3-87e485107370.png)

It only happens on login. Based on stackoverflow there might be a google API key somewhere that needs to have some referers added to it but I dont know where. 

I thought maybe the list of allowed referers was in the code somewhere but if so I cant find it. 

Maybe it will go away once the SSL cert issue resolves.. but looking at this error I'm guessing not .

**Comment by qdozaq** [comment]
Needed to whitelist the domain the gcp and firebase console
