### ISSUE TITLE
"Volunteer with us" screen layout looks a bit whack

### ISSUE THREAD

**Issue by utunga** [factn/resilience-app#582]
Still a bit whack - we should remove the word placeholder copy and center that button. 

![image](https://user-images.githubusercontent.com/166867/82283824-95559680-99eb-11ea-96ab-5ef0a02a2320.png)

I mean the rest of the 'sign up as a volunteer' flow also needs to be tidied up but lets start by getting this page in shape

**Comment by amylo** [comment]
We have to fix the content layout for multiple screens actually. There used to be a `text-align: center` on the App's main CSS file that was originally incorrect. I'm guessing someone fixed it, it really should never have been there in the first place.

So we need to properly style in the theme to center headings and content when we need to, but not forced upon. It seems context dependent, from the design perspective.

**Comment by marekdano** [comment]
Is someone working on it? I can take it.
