### ISSUE TITLE
Facebook login doesnt work / should just be removed from signin - for now

### ISSUE THREAD

**Issue by utunga** [factn/resilience-app#586]
**Steps to reproduce**
1. Logout then visit sign in at https://mutualaid-757f6.web.app/login

**Expected result**
Either facebook login works or facebook login is not available 

**Actual result**
![image](https://user-images.githubusercontent.com/166867/82313484-876c3980-9a1c-11ea-98b8-c2392505e08b.png)

We have the app half set up https://developers.facebook.com/apps/209906623597994/ but it doesn't work - so let's get back to this, for now, easiest solution to remove it.

**Comment by jwu910** [comment]
Removing the good first issue label, just because I feel that this is more of a firebase configuration. Not a hard task, but little bit of either understanding of the firebase configs, or access to firebase admin panel to select identity management services
