### ISSUE TITLE
On Safari, none of the photos appear on the public homepage – only grey boxes. 

### ISSUE THREAD

**Issue by karenkun** [factn/resilience-app#593]
The file type .webp is not supported in Safari, and since Safari has 52.3% market share of mobile browsing, we should fix this like use .jpg instead of .webp?

<img width="452" alt="Screen Shot 2020-05-19 at 3 11 00 PM" src="https://user-images.githubusercontent.com/2974103/82383781-56234780-99e3-11ea-9905-7f2701536270.png">

**Comment by jwu910** [comment]
Hey @karenkun I just submitted a fix for this 

https://github.com/factn/resilience-app/pull/592

Where were you looking at this? maybe it hadn't been deployed yet

**Comment by karenkun** [comment]
I was checking on https://studiocity.resilienceapp.org

**Comment by utunga** [comment]
Just pushed to production can you confirm its fixed at..
https://studiocity.resilienceapp.org ?

**Comment by karenkun** [comment]
Confirmed its fixed at https://studiocity.resilienceapp.org
