### ISSUE TITLE
Input Component enhancement

### ISSUE THREAD

**Issue by mat10tng** [factn/resilience-app#60]
add a new prop :
* required: boolean
when true, and field is empty, it should tell the user that the field is required

**Comment by Raf-Batista** [comment]
I can try this one if no one is on it.

**Comment by thirdeyeclub** [comment]
> 
> 
> I can try this one if no one is on it.
I was gonna PR this one in a few minutes

**Comment by thirdeyeclub** [comment]
> 
> 
> I can try this one if no one is on it.

Go ahead I couldn't make it work with the way it's currently written

**Comment by mat10tng** [comment]
You are welcome to make any changes to make it work!

**Comment by Raf-Batista** [comment]
This is how I currently have it implemented:

I used state which is updated with onChange

Every input that doesn't have a value when the form is submitted will have the placeholder set to "REQUIRED"

I've never made a PR so I have to do some reading on that. Once I figure that out I will take care of it. I will try to find a better solution to this as well.

**Comment by mat10tng** [comment]
https://github.com/factn/mutualaidworld_frontend/blob/master/CONTRIBUTING.md

**Comment by utunga** [comment]
@Raf-Batista super hoping that this process is not actually too hard for folks that havent made a PR before.. so
(a) if you figure it out let me know what bits were missing from the instructions 
(b) if you get stuck just let me/us know (that said im heading to bed just now,.. but yeah)

Either way, keen to hear how you get on..

**Comment by utunga** [comment]
If you already made your changes locally, probably the easiest way to get back on track is to follow the instructions to create a fork, create a second local copy and just copy your changes in to that directory.

**Comment by Raf-Batista** [comment]
Thanks for the help. I submitted the PR following a guide. I will post the link to it in the frontend channel for anyone who's new to this like me. I appreciate the help and welcome any sort of feedback, advice, and critiques. I want to keep improving and help with this project as much as I can. Cheers!
