### ISSUE TITLE
Phone number not saving via user profile page

### ISSUE THREAD

**Issue by qdozaq** [factn/resilience-app#603]
The phone number is not getting saved to a user's `profile` when updating or saving on the profile page.
It **is** updating the the user's `auth` however.

Steps to reproduce:
- Login via social with a new user
- got to `/user/profile`
- update your phone number
- either check your user in the DB or log out the `profile` object connected to your user.
    - You should see that the `phoneNumber` is empty

**Comment by qdozaq** [comment]
It looks like UID and a bunch of other things aren't getting added either....

**Comment by DrewThomasCorps** [comment]
I don't have time to look into it tonight, but I have a hunch that an error is getting thrown when the data is being sanitized. See dataObjectUtil.ts line 34. The organizationUid is a number in the User object but a string in the database. https://github.com/factn/resilience-app/pull/598 might fix this.

**Comment by qdozaq** [comment]
@DrewThomasCorps I believe I've got it worked out here https://github.com/factn/resilience-app/pull/604
