### ISSUE TITLE
Change logo

### ISSUE THREAD

**Issue by mat10tng** [factn/resilience-app#62]
Designer changed the logo!

**Comment by CSumm** [comment]
Does this need to be brought into storybook? I can do this one while we wait on the answer about the map tooling

**Comment by mat10tng** [comment]
You can ignore storybook now! I think we will skip that in favor for speed!

**Comment by sebassdc** [comment]
@mat10tng is this resolved?

**Comment by mat10tng** [comment]
no

**Comment by sebassdc** [comment]
@mat10tng where can i find the  new logo, do i ask in the UI/UX channel?

**Comment by mat10tng** [comment]
yeah, I see that you already ask em! Sorry about the confusion

**Comment by azmainamin** [comment]
@sebassdc Is this still ongoing?

**Comment by utunga** [comment]
Wait a second.. what? The current logo is SVG?

Is the new one also SVG? Maybe this is why this one became .. tricky?
![image](https://user-images.githubusercontent.com/166867/80180544-191f9b80-8657-11ea-997a-3cf690ea1fa4.png)

**Comment by sahjoo** [comment]
Yeah, looks like the older logo is still in the app. We can export the logo to any file type. So if you want an svg, we can export that wherever you need it. I provided the svg version in slack a while back too
https://mutualaidworld.slack.com/archives/C010VC3EN2G/p1586394211362100?thread_ts=1586385257.357800&cid=C010VC3EN2G

**Comment by sahjoo** [comment]
lol svg isn't supported here so couldn't upload it!
but fyi the logo is being worked on currently so most likely it'll change up again.
