### ISSUE TITLE
Align button, text and images to center on some pages for nicer view.

### ISSUE THREAD

**Issue by marekdano** [factn/resilience-app#620]
I reviewed a few pages and I suggest that buttons, text, and images should be centered.

#### `oops`
<img width="613" alt="Screenshot 2020-05-22 at 20 19 34" src="https://user-images.githubusercontent.com/1914165/82702268-9b58ab00-9c69-11ea-8089-d3572983ab9d.png">

#### `notfound`
<img width="608" alt="Screenshot 2020-05-22 at 20 22 03" src="https://user-images.githubusercontent.com/1914165/82702455-f5597080-9c69-11ea-8a4f-a0dd3346ed17.png">

#### `donate`
<img width="629" alt="Screenshot 2020-05-22 at 20 22 56" src="https://user-images.githubusercontent.com/1914165/82702520-10c47b80-9c6a-11ea-8ba5-4d99356d4ad2.png">

#### `status`
<img width="630" alt="Screenshot 2020-05-22 at 20 15 43" src="https://user-images.githubusercontent.com/1914165/82702376-ce02a380-9c69-11ea-8d98-41d701ac3ffa.png">

**Comment by marekdano** [comment]
I can take this issue if it's ok.

**Comment by qdozaq** [comment]
@marekdano go for it!

These were definitely centered before... I wonder if something happened to the `Page` component?
