### ISSUE TITLE
Repurpose Sign Up page for Edit Profile page

### ISSUE THREAD

**Issue by azmainamin** [factn/resilience-app#75]
Right now, we have Sign In Using FB or Phone, both of which might not include attributes like, Name, Location etc. We need a dedicated Profile Page where users can go and edit their data.

**Comment by Raf-Batista** [comment]
I didn't see this issue on airtable. Is it still open?

**Comment by azmainamin** [comment]
I don't think this has been ported over yet. We are still trying to figure out our signin/signup workflow

**Comment by Raf-Batista** [comment]
No problem. Once things are figured out I will be happy to take on issues that are good for new developers. Thanks.
